# Example secrets.toml file for Streamlit deployment
# Copy this to .streamlit/secrets.toml and fill in your values

# Google OAuth 2.0 Credentials
GOOGLE_CLIENT_ID = "your-client-id-here.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "your-client-secret-here"

# Redirect URI for your deployed app
REDIRECT_URI = "https://your-app-name.streamlit.app"

# Gemini API Key (optional - users can still input manually)
GEMINI_API_KEY = "your-gemini-api-key-here"
