# Google Gemini API Configuration
# Get from https://makersuite.google.com/app/apikey
GEMINI_API_KEY = "your-gemini-api-key-here"

# OpenAI API Configuration  
# Get from https://platform.openai.com/api-keys
OPENAI_API_KEY = "your-openai-api-key-here"

# Anthropic Claude API Configuration
# Get from https://console.anthropic.com/settings/keys
ANTHROPIC_API_KEY = "your-anthropic-api-key-here"

# Optional App Configuration
APP_NAME = "query-fanout-tool"
